### ISSUE TITLE
MuhRec GUI - chrash when clicking logging

### ISSUE THREAD

**Issue by chiaracarminati** [neutronimaging/imagingsuite#22]
often Muhrec crashes when clicking on the logging tab after reconstruction

**Comment by anderskaestner** [comment]
Checked it out on mac. All features are working. Change log level, clear, save. No problem.

**Comment by anderskaestner** [comment]
Confirmed on ubuntu

**Comment by anderskaestner** [comment]
This is probably the solution... also for issue #5 

It appears you're trying to access QtGui classes from a thread other than the main thread. Like in some other GUI toolkits (e.g. Java Swing), that's not allowed. From the Threads and QObjects web page:

    Although QObject is reentrant, the GUI classes, notably QWidget and all its subclasses, are not reentrant. They can only be used from the main thread.

A solution is to use signals and slots for communication between the main thread (where the GUI objects live) and your secondary thread(s). Basically, you emit signals in one thread that get delivered to the QObjects via the other thread. The page I linked to above has a good discussion of this. Actually, the whole section on Thread Support in Qt is a good read.

One potential issue you could run into is that, normally, to get full signals and slots support working across threads, you need to start an event loop in the child thread using QThread::exec() (or the PyQt equivalent) so that signals can be delivered to slots in the QObjects that live there. In your case, it sounds like you're making a blocking call to asyncore.loop(), which will prevent you from doing this. But, if you only need to emit signals in one direction (from the child thread to widgets in the main thread), I don't think you'll have a problem.

**Comment by anderskaestner** [comment]
Problem solved by implementing signals and slots in logviewer and recon dialog.
